# Workflow to run tests

name: CI

on:
  push:
    branches: [ main, kotlin-1.5.21 ]
  pull_request:
    branches: [ main, kotlin-1.5.21 ]

jobs:
  build-and-test:
    strategy:
      fail-fast: false

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Setup Java 9
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '9'
        java-package: jdk
        architecture: x64
    - name: set JDK_9 environment variable for kotlin compiler
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: echo ::set-env name=JDK_9::$(echo $JAVA_HOME)
    - name: Setup Java 11
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '11'
        java-package: jdk
        architecture: x64
    - name: set JDK_11 environment variable
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: echo ::set-env name=JDK_11::$(echo $JAVA_HOME)
    - name: Setup Java 8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: '8'
        java-package: jdk
        architecture: x64
    - name: set JDK 6,7,8 environment variables for kotlin compiler
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      run: echo ::set-env name=JDK_16::$(echo $JAVA_HOME) && echo ::set-env name=JDK_17::$(echo $JAVA_HOME) && echo ::set-env name=JDK_18::$(echo $JAVA_HOME)

    # Checkout
    - uses: actions/checkout@v2

    # Build cache
    - name: Cache Gradle Cache
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}-${{ hashFiles('**/gradle.properties') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Cache gradle wrapper
      uses: actions/cache@v2
      with:
        path: ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

    # Run tests with JDK8
    - name: test with jdk8
      run: ./gradlew --stacktrace --info -PcompilerTestEnabled=true test
    - name: Upload test results for jdk8
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-jdk8
        path: compiler-plugin/build/reports

    # Run tests with JDK9
    # Disabling integration tests for a known jdk bug: https://bugs.openjdk.java.net/browse/JDK-8184940
    - name: test with jdk9
      run: JAVA_HOME=$JDK_9 ./gradlew --stacktrace --info -PcompilerTestEnabled=true :compiler-plugin:test
    - name: Upload test results for jdk9
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-jdk9
        path: compiler-plugin/build/reports

    # Run tests with JDK11
    - name: test with jdk11
      run: JAVA_HOME=$JDK_11 ./gradlew --stacktrace --info -PcompilerTestEnabled=true test
    - name: Upload test results for jdk11
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-reports-jdk11
        path: compiler-plugin/build/reports
